### ISSUE TITLE
Breaking change

### ISSUE THREAD

**Issue by pmsoltani** [Jastor11/phresh-tutorial#2]
Hi.
I came across your post, [configuring a postgresql db with your dockerized fastapi app](https://www.jeffastor.com/blog/pairing-a-postgresql-db-with-your-dockerized-fastapi-app) today and found it very comprehensive.

It seems that the `Databases` library in its recent versions (`>0.4.0`) does not require the installation of `psycopg2`, which is needed for DB migrations.

Just to let you know, this causes a failure in your article's [migration section](https://www.jeffastor.com/blog/pairing-a-postgresql-db-with-your-dockerized-fastapi-app#migrating-our-database) when calling:

```
alembic upgrade head
```

**Comment by Jastor11** [comment]
Amazing. Thank you for letting me know! Definitely something I'll take a look at. 

I also appreciate the kind words about the post.

The plan is to modernize all of those original posts as they're almost a year old now, so I'll take that into consideration when I get around to it.

Let me know if you come across anything else that seems off.

**Comment by pmsoltani** [comment]
Sounds good! I will!

BTW, I'm thinking about translating your course (with some modifications) and publish it for free (like the original content). Would you be open to that?

**Comment by Jastor11** [comment]
Absolutely! Thanks for doing that. 

If you send me a link to the translated content version, I'll include it as a link in the original posts as well.

Also, please include a link to the original posts in your translated publishing :-)

**Comment by pmsoltani** [comment]
Great 🎉

As I said, it's only a thought for now... but if it happens, you'll be the first to know.

> Also, please include a link to the original posts in your translated publishing :-)

Goes without saying... (credit where credit is due, right? 😉)

Thanks again.
