### ISSUE TITLE
Could not satisfy psycopg2-binary requirement

### ISSUE THREAD

**Issue by SJDunkelman** [Jastor11/phresh-tutorial#3]
Your tutorial has been great for getting started with Docker but I can't build on macOS once I get to the point of adding the databases[postgresql]==0.3.1 to requirements.txt. 

I've tried adding 'RUN pip3 install psycopg2-binary' to Docker file as well as adding to requirements but it still can't find the binary, any help would be greatly appreciated.

Spec:
macOS 11.1 Big Sur M1 Silicon Apple Chip MBP

**Comment by SJDunkelman** [comment]
databases[postgresql]==0.3.1 needed to be updated to 0.4.2 - now works.

**Comment by Jastor11** [comment]
Ah fantastic. Good to know. 

Bumped the version across tutorials so hopefully that issue is resolved.
