### ISSUE TITLE
ModuleNotFoundError: No module named 'app'

### ISSUE THREAD

**Issue by neruve** [Jastor11/phresh-tutorial#4]
When I try to run the container I get the no module named 'app' error. I have no idea what is going on. I even cloned this github repo and tried to run it and got the same thing. Here is what it gives me:

phresh_server_1 is up-to-date
Attaching to phresh_server_1
server_1  | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
server_1  | INFO:     Started reloader process [1]
server_1  | Process SpawnProcess-1:
server_1  | Traceback (most recent call last):
server_1  |   File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
server_1  |     self.run()
server_1  |   File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
server_1  |     self._target(*self._args, **self._kwargs)
server_1  |   File "/usr/local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 61, in subprocess_started
server_1  |     target(sockets=sockets)
server_1  |   File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 382, in run
server_1  |     loop.run_until_complete(self.serve(sockets=sockets))
server_1  |   File "uvloop/loop.pyx", line 1494, in uvloop.loop.Loop.run_until_complete
server_1  |   File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 389, in serve
server_1  |     config.load()
server_1  |   File "/usr/local/lib/python3.8/site-packages/uvicorn/config.py", line 288, in load
server_1  |     self.loaded_app = import_from_string(self.app)
server_1  |   File "/usr/local/lib/python3.8/site-packages/uvicorn/importer.py", line 23, in import_from_string
server_1  |     raise exc from None
server_1  |   File "/usr/local/lib/python3.8/site-packages/uvicorn/importer.py", line 20, in import_from_string
server_1  |     module = importlib.import_module(module_str)
server_1  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
server_1  |     return _bootstrap._gcd_import(name[level:], package, level)
server_1  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
server_1  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
server_1  |   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
server_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
server_1  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
server_1  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
server_1  |   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
server_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
server_1  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
server_1  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
server_1  |   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
server_1  | ModuleNotFoundError: No module named 'app' 

What is wrong. I don't understand. I am doing this on a windows machine, but a container is a container, it shoudln't matter.

**Comment by neruve** [comment]
Looks like it had to do with volume mapping in windows. I removed the volume mapping and ran the container and it seems to be working fine.

**Comment by Jastor11** [comment]
Interesting. Haven't tried it on a windows machine, but that's good to know. I'll add a message about this to the post when I publish the next one.

Thanks for pointing that out.

**Comment by neruve** [comment]
I switched over to ubuntu to make this a little more 'tutorial-like' but now I can't get past the connection to postgres step. I love computers and learning the programming side but I don't think I've every just had something work. (stupid things that aren't the same, seems like some people can run docker commands without sudo, i cannot etc)

That's besides the point.  What is odd is I can bash into the postgres container run postgress://postgres:postgres@db./postgres and it seems to connect fine. However from the python code, the same DATABASE_URL (i checked) doesn't work, it just times out. Also, FYI, timeout errors don't have an exception message in the databases package, so it took me a while to figure that out as the log would just be:

--- DB CONNECTION ERROR ---

--- DB CONNECTION ERROR ---

Any insight would be appreciated.
